---
ntp_config_server:
  - sjc1ads01.emt.hobsons.local
  - sjc1ads02.emt.hobsons.local

nameserver_config: 
  - 10.24.132.5
  - 10.24.132.6

splunk_server: sjc1-splunk
splunk_port: 9997

logicm_collector: EMT\SJC1PU-LOGICM01
