---
- name: Install ntp, if needed
  yum: name={{ item }} state=present
  with_items:
   - ntp
   - ntpdate
  tags: ntp

- name: Copying ntp.conf & setting permissions
  template: src=ntp.conf dest=/etc/ mode=644
  tags: ntp

- name: Enable ntpd at startup
  service: name=ntpd enabled=yes
  tags: ntp

- name: Stop ntpd if it's running
  service: name=ntpd state=stopped
  tags: ntp

- name: Sync the date
  command: /usr/sbin/ntpdate {{ ntp_server1 }}
  tags: ntp

- name: Start ntpd
  service: name=ntpd state=started
  tags: ntp
