---
- name: Setup EPEL repo
  yum: name=epel-release state=present

- name: Install nginx
  yum: name=nginx state=present

- name: Enable nginx at startup
  service: name=nginx enabled=yes

- name: Stop nginx if it's running
  service: name=nginx state=stopped

- name: Start nginx
  service: name=nginx state=started

