---
- name: Install ClamAV
  yum: name={{ item }} state=present
  with_items:
   - clamd
   - clamav
   - clamav-db
   - clamav-milter

- name: Run freshclam to check for database updates
  command: freshclam --no-warnings
  register: freshclam
  changed_when: freshclam.stdout.find("updated") != -1

- name: Enable ClamAV on startup
  service: name=clamd enabled=yes
