---
- name: Setup MongoDB yum repo
  copy: src=mongodb-3.2.repo dest=/etc/yum.repos.d/
  tags: mongodb_install

- name: Install MongoDB
  yum: name={{ item }} state=latest
  with_items:
    - mongodb-org-3.2.1
    - mongodb-org-server-3.2.1
    - mongodb-org-shell-3.2.1
    - mongodb-org-mongos-3.2.1
    - mongodb-org-tools-3.2.1
  tags: mongodb_install

- name: Add iptables rules
  command: iptables -I INPUT -m tcp -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "MongoDB"
  with_items:
    - 27017
    - 27018
    - 27019
    - 28017

- name: Saving iptables changes
  shell: iptables-save > /etc/sysconfig/iptables

- name: Enable MongoDB at startup
  service: name=mongod enabled=yes
  tags: mongodb_install
