---
- name: Update sudoers 6
  template:
    dest=/etc/sudoers.d/hobsons
    src=etc/sudoers.d/hobsons
    mode=0440
    owner=root
    group=root
    force=yes
    validate='visudo -cf %s'
  when: ansible_distribution_major_version == "6"

- name: Update sudoers 5
  lineinfile:
    "dest=/etc/sudoers
    line='ansi    ALL=(ALL)       NOPASSWD: ALL'
    validate='visudo -cf %s'"
  when: ansible_distribution_major_version == "5"
