---
# Deploy new host from template
- name: Deploy host from template
  vsphere_guest:
    vcenter_hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    guest: "{{ vmware_guest_name }}"
    from_template: yes
    template_src: "{{ vmware_guest_template }}"
#    cluster: "{{ vmware_cluster }}"
#    resource_pool:  "{{ vmware_resource_pool }}"
    esxi:
      datacenter: "{{ vmware_datacenter }}"
      hostname: "{{ vmware_cluster_hostname }}"
    vm_extra_config:
      folder: "{{ vmware_vcenter_guest_folder }}"
  tags:
    - deploy

# Gather facts about a guest
- name: Gather VM guest facts
  vsphere_guest:
    vcenter_hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    guest: "{{ vmware_guest_name }}"
    vmware_guest_facts: yes
  tags:
   - gather_facts
