---
# Prepare firstrun.sh script to be run post kickstart
- name: Setup post-kick script
  template: src=firstrun.sh.j2 dest=/opt/kickstart/firstrun.sh owner=nginx group=nginx mode=0755
  tags:
    - kick_prep
 
# Deploy new host from kickstart
- name: Deploy new host
  vsphere_guest:
    vcenter_hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    guest: "{{ vmware_guest_name }}"
    state: powered_on
#    from_template: yes
#    template_src: "{{ vmware_guest_template }}"
#    cluster: "{{ vmware_cluster }}"
#    resource_pool:  "{{ vmware_resource_pool }}"
    esxi:
      datacenter: "{{ vmware_datacenter }}"
      hostname: "{{ vmware_cluster_hostname }}"

    # More than one disk & nic can be created.  Be sure to update vars.
    vm_disk:
     disk1:
       size_gb: "{{ vmware_disk01_size_gb }}"
       type: thin
       datastore: "{{ vmware_datastore01 }}"
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{ vmware_network01 }}"
        network_type: standard

    vm_hardware:
      memory_mb: "{{ vmware_hw_memory_mb }}"
      num_cpus: "{{ vmware_hw_num_cpus }}"
      osid: centos64Guest
      scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "sjc1vm4dsprod01/ISO/CentOS-6.7-x86_64-kick.iso"
      # Uncomment the following if needed
      #vm_floppy:
      #  type: "image"
      #  image_path: "DatastoreName/floppy-image.flp"

    vm_extra_config:
      folder: "{{ vmware_vcenter_guest_folder }}"

  tags:
    - deploy

# Gather facts about a guest
- name: Gather VM guest facts
  vsphere_guest:
    vcenter_hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    guest: "{{ vmware_guest_name }}"
    vmware_guest_facts: yes
  tags:
   - gather_facts

# Destroy a VM
- name: Destroy VM
  vsphere_guest:
    vcenter_hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    guest: "{{ vmware_guest_name }}"
    state: absent
    force: yes
  tags:
    - destroy
