---
- name: Download & Install Splunk 
  yum: name=http://sjc1du-ansible01.emt.hobsons.local/pkg/splunk-6.3.3-f44afce176d0-linux-2.6-x86_64.rpm state=present
  tags: splunk

- name: Enable startup & accept license
  command: /opt/splunk/bin/splunk enable boot-start --accept-license

- name: Disable webserver
  command: /opt/splunk/bin/splunk disable webserver

- name: Configure Splunk Inputs
  template: src=inputs.conf.j2 dest=/opt/splunk/etc/system/local/inputs.conf owner=splunk group=splunk mode=0644

- name: Configure Splunk Outputs
  template: src=outputs.conf.j2 dest=/opt/splunk/etc/system/local/outputs.conf owner=splunk group=splunk mode=0644
  notify: restart splunk
  tags: splunk

- name: Adding iptables rules for splunkd
  command: iptables -I INPUT -m tcp -p tcp--dport {{ item }} -j ACCEPT -m comment --comment "Splunk Port"
  with_items:
    - 8000
    - 8089
    - 9997
    - 8080
    - 514
  tags: rabbitmq_iptables

- name: Saving iptables changes
  shell: iptables-save > /etc/sysconfig/iptables
  tags: rabbitmq_iptables

