---
- name: Download & Install erlang
  get_url: url=https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_18.2-1~centos~6_amd64.rpm dest=/root/esl-erlang_18.2-1~centos~6_amd64.rpm
  yum: name=http://sjc1du-ansible01.emt.hobsons.local/emt/esl-erlang_18.2-1~centos~6_amd64.rpm state=present
  tags: erlang

- name: Download & Install rabbitmq
  rpm_key: key=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present
  yum: name=http://sjc1du-ansible01.emt.hobsons.local/pkg/rabbitmq-server-3.6.1-1.noarch.rpm state=present
  tags: rabbitmq

- name: Enable rabbitmq management plugin
  notify: start rabbitmq-server
  command: rabbitmq-plugins enable rabbitmq_management
  tags: rabbitmq

- name: Adjust limits for rabbitmq user
  pam_limits: domain=rabbitmq limit_type=soft limit_item=nofile value=65536
  pam_limits: domain=rabbitmq limit_type=hard limit_item=nofile value=65536

- name: Adding additional parameters to rabbitmq configuration
  copy: src=rabbitmq-add.config dest=/root/rabbitmq-add.config
  command: cat /root/rabbitmq-add.config >> /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq-server
  tags: rabbitmq

- name: Create rabbitmq user account, delete guest account
  command: rabbitmqctl add_user mquser PASSWORD
  command: rabbitmqctl set_permissons mquser ".*" ".*" ".*"
  command: rabbitmqctl set_user_tags msquser administrator
  command: rabbitmqctl delete_user guest
  tags: rabbitmq

- name: Create HA Policies for AR/AY queues
  command: rabbitmqctl set_policy "AR Mirrored Queues" "^AR\." '{"ha-mode":"all"}'
  command: rabbitmqctl set_policy "AY Mirrored Queues" "^AY\." '{"ha-mode":"all"}'
  tags: rabbitmq
