---
- name: Download & Install erlang
  yum: name=http://sjc1du-ansible01.emt.hobsons.local/pkg/erlang-18.2-1.el6.x86_64.rpm state=present
#  yum: name=http://sjc1du-ansible01.emt.hobsons.local/pkg/esl-erlang_18.2-1~centos~6_amd64.rpm state=present
  tags: erlang_install

- name: Get rabbitmq signing key
  rpm_key: key=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present
  tags: rabbitmq_install

- name: Download & Install rabbitmq
  yum: name=http://sjc1du-ansible01.emt.hobsons.local/pkg/rabbitmq-server-3.6.1-1.noarch.rpm state=present
#  command: rpm -ivh --nodeps http://sjc1du-ansible01.emt.hobsons.local/pkg/rabbitmq-server-3.6.1-1.noarch.rpm
  tags: rabbitmq_install

- name: Adding iptables rules for rabbitmq
  command: iptables -A INPUT -m tcp -p tcp --dport {{ item }} -j ACCEPT
  with_items:
    - 5672
    - 15672
  tags: rabbitmq_iptables

- name: Saving iptables changes
  command: /etc/init.d/iptables save
  tags: rabbitmq_iptables

- name: Ensure iptables enabled at startup
  service: name=iptables enabled=yes

- name: Enable rabbitmq management plugin
  command: rabbitmq-plugins enable rabbitmq_management
  tags: rabbitmq_config

- name: Adjust soft nofile limits for rabbitmq user
  lineinfile: dest=/etc/security/limits.conf line="rabbitmq        soft    nofile          65536" 
  tags: rabbitmq_config

- name: Adjust hard nofile limits for rabbitmq user
  lineinfile: dest=/etc/security/limits.conf line="rabbitmq        hard    nofile          65536" 
  tags: rabbitmq_config

- name: Adding additional parameters to rabbitmq configuration
  copy: src=rabbitmq-add.config dest=/etc/rabbitmq/rabbitmq.config owner=root group=root mode=0755
  tags: rabbitmq_config

# Because the handlers aren't working for some reason...
- name: Stop rabbitmq
  service: name=rabbitmq-server state=stopped
  tags: rabbitmq_config

- name: Start rabbitmq
  service: name=rabbitmq-server state=started
  tags: rabbitmq_config

- name: Enable rabbitmq at startup
  service: name=rabbitmq-server enabled=yes
  tags: rabbitmq_config

- name: Create rabbitmq user account
  command: rabbitmqctl add_user mquser {{ rabbitmq_user_pass }}
  tags: 
   - rabbitmq_users
   - rabbitmq_config

- name: Delete guest account
  command: rabbitmqctl delete_user guest
  tags: 
   - rabbitmq_users
   - rabbitmq_config

- name: Set account permissions
  command: rabbitmqctl set_permissions mquser ".*" ".*" ".*"
  tags: 
   - rabbitmq_users
   - rabbitmq_config

- name: Set rabbitmq user tags
  command: rabbitmqctl set_user_tags mquser administrator
  tags: 
   - rabbitmq_users
   - rabbitmq_config

- name: Create HA Policies for AR queues
  command: rabbitmqctl set_policy "AR Mirrored Queues" "^AR\." '{"ha-mode":"all"}'
  tags: 
   - rabbitmq_policy
   - rabbitmq_config

- name: Create HA Policies for AY queues
  command: rabbitmqctl set_policy "AY Mirrored Queues" "^AY\." '{"ha-mode":"all"}'
  tags: 
   - rabbitmq_policy
   - rabbitmq_config

- name: Add splunk monitoring
  lineinfile: "dest=/opt/splunk/etc/system/local/inputs.conf line='[monitor:///var/log/rabbitmq/rabbit@{{ ansible_hostname }}.log]'"
  tags: rabbitmq_splunk

- name: Restart Splunk
  command: /etc/init.d/splunk restart
  tags: rabbitmq_splunk
