---
# Deploy new host from kickstart
- name: Deploy new host
  vsphere_guest:
    vcenter_hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    guest: "{{ vmware_guest_name }}"
    state: powered_on
    esxi:
      datacenter: "{{ vmware_datacenter }}"
      hostname: "{{ vmware_cluster_hostname }}"

    vm_disk:
     {{ item[0] }}:
        size_gb: {{ item[1] }}
        type: thin
        datastore: "{{ vmware_datastore01 }}"
     with_nested:
       - "{{ vmware_disk }}"
       - "{{ vmware_disk_size }}"

    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{ vmware_network01 }}"
        network_type: standard

    vm_hardware:
      memory_mb: "{{ vmware_hw_memory_mb }}"
      num_cpus: "{{ vmware_hw_num_cpus }}"
      osid: "{{ vmware_os_guest_id }}"
      scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "{{ vmware_iso_path }}"
      # Uncomment the following if needed
      #vm_floppy:
      #  type: "image"
      #  image_path: "DatastoreName/floppy-image.flp"

    vm_extra_config:
      folder: "{{ vmware_vcenter_guest_folder }}"

  tags:
    - deploy
