---
- name: Install yum-cron.
  sudo: yes
  yum:
    name: yum-cron
    state: present

- name: Copy the configuration file (CentOS 6).
  sudo: yes
  template:
    src: etc/sysconfig/yum-cron.j2
    dest: /etc/sysconfig/yum-cron
  notify:
    - restart yum-cron
  when: ansible_distribution_version < 7

- name: Copy the configuration file (CentOS 7).
  sudo: yes
  template:
    src: etc/yum/yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
  notify:
    - restart yum-cron
  when: ansible_distribution_version >= 7

- name: Start yum-cron.
  sudo: yes
  service:
    name: yum-cron
    state: running
    enabled: yes