---
# CentOS 6.
yum_cron_check_only: 'no'
yum_cron_check_first: 'no'
yum_cron_download_only: 'no'
yum_cron_mailto: 'shawn.green@hobsons.com'
yum_cron_systemname: '{{ ansible_hostname }}'
yum_cron_days_of_week: 6

# Centos 7.
yum_cron_update_cmd: security
yum_cron_update_messages: 'yes'
yum_cron_download_updates: 'yes'
yum_cron_apply_updates: 'no'
yum_cron_random_sleep: 360
yum_cron_system_name: None
yum_cron_output_width: 80
yum_cron_email_from: 'root@{{ ansible_hostname }}'
yum_cron_email_to: 'shawn.green@hobsons.com'
yum_cron_email_host: '{{ ansible_hostname }}'
yum_cron_group_list: None
yum_cron_group_package_types: 'mandatory, default'
yum_cron_debug_level: -2
yum_cron_mdpolicy: 'group:main'
