---
- name: Adding iptables rules for rabbitmq clustering
  command: iptables -A INPUT -m tcp -p tcp --dport {{ item }} -j ACCEPT
  with_items:
    - 4369
    - 25672
  tags: rabbitmq_iptables

- name: Saving iptables changes
  command: /etc/init.d/iptables save
  tags: rabbitmq_iptables

- name: Restart iptables
  service: name=iptables state=restarted

- name: Ensure iptables enabled at startup
  service: name=iptables enabled=yes

- name: Stopping rabbitmq app
  command: rabbitmqctl stop_app

#- name: Resetting rabbitmq app
#  command: rabbitmqctl reset

- name: Stopping rabbitmq-server
  service: name=rabbitmq-server state=stopped

- name: Copy erlang cookie
  template: src=erlang.cookie.j2 dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400 backup=yes

- name: Restarting rabbitmq-server on master
  service: name=rabbitmq-server state=restarted
  when: inventory_hostname == "{{ rabbitmq_master }}"

- name: Starting rabbitmq app on master
  command: rabbitmqctl start_app
  register: cluster_master
  when: inventory_hostname == "{{ rabbitmq_master }}"

- name: Sending sigterm to any running rabbitmq processes
  shell: pkill -u rabbitmq || true
  when: inventory_hostname != "{{ rabbitmq_master }}"

- name: Restarting rabbitmq-server
  service: name=rabbitmq-server state=restarted
  when: inventory_hostname != "{{ rabbitmq_master }}"

- name: Stopping rabbitmq app
  command: rabbitmqctl stop_app
  when: inventory_hostname != "{{ rabbitmq_master }}"

#- name: Resetting rabbitmq app
#  command: rabbitmqctl reset
#  when: inventory_hostname != "{{ rabbitmq_master }}"

- name: Joining rabbitmq cluster
  command: rabbitmqctl join_cluster 'rabbit@{{ rabbitmq_master }}'
  register: cluster_joined
  when: inventory_hostname != "{{ rabbitmq_master }}"

- name: Starting rabbitmq app
  command: rabbitmqctl start_app
  when: inventory_hostname != "{{ rabbitmq_master }}"

- name: Marking as clustered
  file: path=/etc/rabbitmq/clustered state=touch
  when: cluster_master.changed or cluster_joined.changed
