---
- name: Install requisite packages, if needed
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - yum-plugin-security
   - man
   - wget
   - curl
   - sssd-client
   - epel-release

- name: Copy /etc/resolv.conf
  template: src=etc/resolv.conf.j2 dest=/etc/resolv.conf mode=644

- name: Stop iptables
  service: name=iptables state=stopped

- name: Copy base iptables
  copy: src=iptables dest=/etc/sysconfig/iptables mode=644 

- name: Ensure iptables in enabled
  service: name=iptables enabled=yes

- name: Ensure selinux is disabled
  selinux: state=disabled

- name: Start iptables
  service: name=iptables state=started
