---
- name: Install requisite packages, if needed
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - yum-plugin-security
   - man
   - wget
   - curl
   - sssd-client
   - epel-release

- name: Copy /etc/resolv.conf
  template: src=etc/resolv.conf.j2 dest=/etc/resolv.conf mode=644

- name: Stop iptables
  service: name={{ item }} state=stopped
  with_items:
   - iptables
   - ip6tables

- name: Disable iptables on startup
  service: name={{ item }} enabled=no
  with_items:
   - iptables
   - ip6tables

- name: Ensure selinux is disabled
  selinux: state=disabled
