---
- name: Install requisite packages, if needed
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - yum-plugin-security
   - man
   - wget
   - curl
   - sssd-client

- name: Copy /etc/resolv.conf
  template: src=etc/resolv.conf.j2 dest=/etc/resolv.conf mode=644
