---
- name: Install requisite packages, if needed
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - yum-plugin-security
   - ntp
   - ntpdate
   - man
   - wget
   - curl
   - sssd-client
