---
# VMware provisioning

- hosts: localhost

  vars:
    - vmware_vcenter_hostname: 'sjc1-vmmngt01.emt.hobsons.local'
    - vmware_guest_name: 'sjc1du-ansitest01'
    - vmware_vcenter_hostname: 'sjc1-vmmngt01.emt.hobsons.local'
    - vmware_datacenter: 'SJC1-VMWare'
    - vmware_cluster: 'SJC1_VMCluster3_QA_DEV_STAGING_DR'
    - vmware_cluster_hostname: 'sjc1-04a-01-vmhost.emt.hobsons.local'
    - vmware_vcenter_guest_folder: 'Utilities'
    - vmware_network01: 'VM Network Ethernet - 128'
    - vmware_datastore01: 'sjc1vm4dsqadev02'
    - vmware_hw_memory_mb: '2048'
    - vmware_hw_num_cpus: '2'
    - vmware_os_guest_id: 'centos64Guest'
#    - vmware_os_guest_id: 'rhel6_64Guest'
    - vmware_iso_path: 'sjc1vm4dsprod01/ISO/CentOS-6.7-x86_64-kick.iso'
    - vmware_disks:
         disk1:
           disk_size: 20
         disk2:
           disk_size: 80
#         - { name: 'disk1', size: '20' }
#         - { name: 'disk2', size: '80' }

  roles:
    - vmware-test

