---
- name: Deploy LogicMonitor Host
  local_action: >
    logicmonitor
    target=host
    action=add
    hostname='{{ logicm_hostname }}'
    displayname='{{ logicm_hostname }}'
    collector='{{ logicm_collector }}'
    company='{{ logicm_company }}'
    user='{{ logicm_user }}'
    password='{{ logicm_password }}'
    groups="{{ logicm_group }}"
    properties="{'system.categories':'Netsnmp,snmp,snmpTCPUDP,snmpHR'}"
