---
# Example playbook for setting up software on a host.
# If a new inventory host, run this after running client_setup playbook
# 
# Set the hosts: below to the appropriate host group in the inventory
# OR
# Run this playbook using the -l flag to limit the hosts
#	Ex. ansible-playbook ayprx.yml -l HOSTNAME_USED_IN_INVENTORY

- hosts: all
  remote_user: ansi
  become: true
  become_user: root
  become_method: sudo

  roles:
    - common
