---
# Configure rabbitmq clustering

- hosts: all
  remote_user: ansi
  become: true
  become_user: root
  become_method: sudo

  vars:
    - rabbitmq_master: iad1pu-aprrab03

  roles:
    - rabbitmq-cluster
