---
# VMware provisioning

######
# Documentation: https://confluence.naviance.com/display/Techops/Ansible+Linux+Provisioning
# Use this playbook as a template.
#
# Create a copy & update the vars as needed. 
# 
# vmware_os_guest_id options:
#   CentOS - centos64Guest
#   RHEL - rhel6_64Guest
# 
# vmware_iso_path options:
#   CentOS 6.7 SJC1 - sjc1vm4dsprod01/ISO/CentOS-6.7-x86_64-kick.iso
#   CentOS 6.7 IAD1 - iad1vm3dsbuild0/ISO's/CentOS-6.7-x86_64-kick.iso
#   CentOS 6.7 LHR1 - vmdatastore01/ISO/CentOS-6.7-x86_64-kick.iso
#   RHEL 6 SJC1 - sjc1vm4dsprod01/ISO/rhel-6u5-x86_64-kick.iso
#   RHEL 6 IAD1 - iad1vm3dsbuild0/ISO's/rhel-6u5-x86_64-kick.iso
#   RHEL 6 LHR1 - vmdatastore01/ISO/rhel-6u5-x86_64-kick.iso
#
# To run: $ ansible-playbook myprovisioning.yml --tags "kick_prep,deploy"
#
######

- hosts: localhost

  vars:
    - vmware_guest_name: 'sjc1du-ansitest01'
    - vmware_vcenter_hostname: 'sjc1-vmmngt01.emt.hobsons.local' 
    - vmware_datacenter: 'SJC1-VMWare'
    - vmware_cluster: 'SJC1_VMCluster3_QA_DEV_STAGING_DR'
    - vmware_cluster_hostname: 'sjc1-04a-01-vmhost.emt.hobsons.local'
    - vmware_vcenter_guest_folder: 'Utilities'
    - vmware_network01: 'VM Network Ethernet - 128'
    - vmware_datastore01: 'sjc1vm4dsqadev02'
    - vmware_disk01_size_gb: '20'
    - vmware_hw_memory_mb: '2048'
    - vmware_hw_num_cpus: '2'
    - vmware_os_guest_id: 'centos64Guest'
    - vmware_iso_path: 'sjc1vm4dsprod01/ISO/CentOS-6.7-x86_64-kick.iso'

  roles:
    - vmware-guest-prep
    - vmware-guest-manage

