---
# Configure rabbitmq clustering
# lhr erlang cookie - YDNVVSSFLDIMGBLLTFDG
# iad erlang cookie - BCSAKKOYYEWCHMJWQUIV

- hosts: all
  remote_user: ansi
  become: true
  become_user: root
  become_method: sudo

  vars:
    - rabbitmq_master: lhr1pu-aprrab03
    - erlang_cookie: YDNVVSSFLDIMGBLLTFDG


  roles:
    - rabbitmq-cluster
