# Playbook to change the root password on any given (or all) servers
# *** OPTION 1)
#	Change the "hosts" below to the host or host group you want to
#	run this playbook against
# *** OPTION 2)
#	Define the host at the commandline:
#		$ ansible-playbook root_password.yml -l IP 
#
# Generate password hash using the following command:
# $ python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
#
# 20160407 - Hash for current HE root password
#	$6$rounds=656000$LQTN03HNNepnGjst$GUsTqZNUFmw8R8Su2xKUM0Ubcv6mgB5Sp7IkX6tgRiAr1t4oWC.aq1X2C1Dx0IPzehv7RNB8FiTNaGc6yuncH/

- hosts: ayprx
  tasks:
  - name: Change root password
    user: name=root update_password=always password="$6$rounds=656000$LQTN03HNNepnGjst$GUsTqZNUFmw8R8Su2xKUM0Ubcv6mgB5Sp7IkX6tgRiAr1t4oWC.aq1X2C1Dx0IPzehv7RNB8FiTNaGc6yuncH/"
