---
# VMware provisioning

######
# Documentation: https://confluence.naviance.com/display/Techops/Ansible+Linux+Provisioning
# Use this playbook as a template.
#
# Create a copy & update the vars as needed. 
#
# Odd number hosts go on datastore cluster 3
# Even number hosts go on datastore cluster 4
# 
# To run: $ ansible-playbook myprovisioning.yml --tags "kick_prep,deploy"
#
######

- hosts: localhost

  vars:
    - vmware_guest_name: 'iad1pu-kfprov01'
    - vmware_vcenter_hostname: 'iad1-vmmngt01.emt.hobsons.local' 
    - vmware_datacenter: 'IAD1-VMWare'
    - vmware_cluster: 'IAD1 VMCluster1 - PROD'
    - vmware_cluster_hostname: 'iad1-07a-01-vmhost.emt.hobsons.local'
    - vmware_vcenter_guest_folder: 'Utilities'
    - vmware_network01: 'VM Network Ethernet'
    - vmware_datastore01: 'iad1vm4dsprod01'
    - vmware_disk01_size_gb: '30'
    - vmware_hw_memory_mb: '8192'
    - vmware_hw_num_cpus: '2'
    - vmware_os_guest_id: 'centos64Guest'
    - vmware_iso_path: "iad1vm3dsbuild0/ISO's/CentOS-6.7-x86_64-kick.iso"

  roles:
    - vmware-guest-prep
    - vmware-guest-manage

